### ISSUE TITLE
Question: seems not to be ready to load an existing RWKV model using `from_pretrained`

### ISSUE THREAD

**Issue by webpolis** [Hannibal046/nanoRWKV#1]
Am I right to affirm this isn't yet prepared to do something like the following?:

`LLM.from_pretrained('RWKV-4-World-0.4B-v1-20230529-ctx4096', 'rwkv')`

https://github.com/Hannibal046/nanoRWKV/blob/f36de8a3c2c852e610112d2789acf6b45f8c9f6f/train.py#L162

**Comment by Hannibal046** [comment]
yes, you are right. Currently it doesn't support loading from trained ckpt. Because RWKV uses different tokenizer from GPT-2 and our primary goal is to compare RWKV with GPT. So loading RWKV pre-trained weight is not our priority. But we will do it as you can see it is listed in the `to-do list` section.

Actually, it is almost done. You could check this (Welcome PR if you are interested): https://github.com/Hannibal046/nanoRWKV/blob/f36de8a3c2c852e610112d2789acf6b45f8c9f6f/modeling_rwkv.py#L379-L401

**Comment by Hannibal046** [comment]
hi, @webpolis , we have complete `from_pretrained` method, you could use this snippet to check:
```python
from modeling_rwkv import RWKV
model_types = ['RWKV/rwkv-4-169m-pile',
            "RWKV/rwkv-4-430m-pile",
            "RWKV/rwkv-4-1b5-pile",
            "RWKV/rwkv-4-3b-pile",
            "RWKV/rwkv-4-7b-pile",
            "RWKV/rwkv-raven-7b",
            "RWKV/rwkv-raven-1b5",
            "RWKV/rwkv-raven-3b",]
for model_type in model_types:
    model = RWKV.from_pretrained(model_type,use_customized_cuda_kernel=False)
```

**Comment by webpolis** [comment]
Thank you @Hannibal046 ! I'll try it out.
