### ISSUE TITLE
Correct usage of T_MAX

### ISSUE THREAD

**Issue by theodorblackbird** [Hannibal046/nanoRWKV#6]
Hi,
I'm playing around with this repo and facing the case where I want to train on sequence of length > 1024.
Setting block_length > 1024 accordingly seems a natural choice since it's a model parameter. 
However I found that I also need to manually tune T_MAX parameter which is by default fixed to 1024 and prevents me to train on longer sequences. It seems to work but I have some doubts, it must have a reason why they're not by default logically linked together right ? Could you explain how should I properly use them ?
Thank you for this amazing repo

**Comment by Hannibal046** [comment]
Hi, thanks for asking. This is actually because of the alignment with original nanoGPT. Your are right, this is just a model parameters and should be configurable.

The following is the updated version and has been tested on my side:
https://github.com/Hannibal046/nanoRWKV/blob/1d61d49df72f593a030cdd3cb1b4423e68c31d18/modeling_rwkv.py#L599
